services:
  db:
    image: postgres:16-alpine
    restart: unless-stopped
    environment:
      POSTGRES_USER: scrobbler
      POSTGRES_PASSWORD: scrobbler
      POSTGRES_DB: scrobbler
    ports:
      - '5432:5432'
    volumes:
      - scrobbler_pgdata:/var/lib/postgresql/data
    healthcheck:
      test: ['CMD-SHELL', 'pg_isready -U scrobbler']
      interval: 5s
      timeout: 5s
      retries: 5

volumes:
  scrobbler_pgdata:
